name: Deploy to Amazon ECS

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: us-east-2

  ECS_CLUSTER: Ecs-demo
  ECS_SERVICE: my-ecs-service
  ECS_TASK_DEFINITION_FILE: taskdefinition.json
  CONTAINER_NAME: react-app


jobs:

  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-2
      REGISTRY: ghcr.io
      IMAGE_NAME: harish9395/react-mobile-app
      IMAGE_TAG: ${{ github.sha }}

    steps:

      - name: Checkout source
        uses: actions/checkout@v4

      -  name: Login to GitHub Container Registry
         uses: docker/login-action@v3
         with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}


      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2


      - name: Build and tag image
        id: build-image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          echo "image=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}" >> $GITHUB_OUTPUT

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
            role-to-assume: arn:aws:iam::728327099276:role/GithubECSDeployIAMRole
            aws-region: ${{ secrets.AWS_REGION }}


      #Deploy to ECS Dev
      - name: Get code
        uses: actions/checkout@v4
      - name: Render ECS task definition with new image
        id: render-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ env.ECS_TASK_DEFINITION_FILE }}
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ steps.build-image.outputs.image }} 
      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render-task-def.outputs.task-definition }}
          cluster: ${{ env.ECS_CLUSTER }}
          service: ${{ env.ECS_SERVICE }}
          wait-for-service-stability: true
